<?php
/**
 *
 * <%= appName %> Index View
 *
 */
?>

<div id="app-main"></div>

<script type="text/javascript">
    var BootstrappedData = <?= $this->appData; ?>;

<?php if ($this->activateDebug) { ?>
    var Ibp = Ibp || {};
    Ibp.Debug = true;
<?php } ?>

    if (typeof console === 'undefined' || typeof console.log === 'undefined') {
        console = {
            log: function () {}
        };
    }
</script>
